version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=authorization
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data
  auth_form_app:
    container_name: auth_form_app
    image: auth_form_app # Specify the name of the Docker image to be built
    depends_on:
      - db
      - alembic_migrations
    environment:
      REAL_DATABASE_URL: "postgresql+asyncpg://ksyu7650:04042002Mm!@db:18003/ksyu7650"
      APP_PORT: "8000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
  alembic_migrations:
    container_name: alembic_migrations
    image: alembic_migrations # Specify the name of the Docker image to be built
    depends_on:
      - db
    environment:
      ALEMBIC_DATABASE_URL: "postgresql://postgres:123456@db/authorization"
      REAL_DATABASE_URL: "postgresql+asyncpg://postgres:123456@db:5432/authorization"
      APP_PORT: "8001"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - custom

networks:
  custom:
    driver: bridge
volumes:
  db-data:
